# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lukas
tagline:          'Raneburger'
description:      'Online Resume'
url:              http://farnsworth87.github.io
baseurl:          /

author:
  name:           'Lukas Raneburger'
  url:            https://twitter.com/zoidberg87

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/farnsworth87/farnsworth87.github.io
